### ISSUE TITLE
clang: missing header in second pass of orogen typelib call for base/orogen/types

### ISSUE THREAD

**Issue by jmachowinski** [orocos-toolchain/orogen#7]
Hey, 
not sure if this is really an orogen bug, or more one for base/orogen/types.
This is related to the clang integration work.
If using clang to generate the tlb files, the first pass runs through.
Meaning, that the tlbs for all headers from base/types get generated.
Then a second pass happens, were tlbs for the just generated wrappers
are generated. 
During this call a opaque RTT/extra/ReadOnlyPointer<base/samples/Frame> is
given. But there is no header given, that contains a defintion of either 
RTT/extra/ReadOnlyPointer nor base/samples/Frame.

Apart from this problem, what is the expected result ? My guess would
be, that in orogen_includes the header to the definition of 
RTT/extra/ReadOnlyPointer and base/samples/Frame should be
registered, seperated by a collonn.

**Comment by doudou** [comment]
OK. This looks stale. I'm not even sure the clang importer works in any way (castxml is definitely the canonical importer)
