### ISSUE TITLE
oroconf extract error

### ISSUE THREAD

**Issue by rafaelsaback** [orocos-toolchain/orogen#72]
After this [commit](https://github.com/orocos-toolchain/orogen/commit/ad4fc2082fe710ee02b29983e4713892efa57e96) when I try to use

``` oroconf extract auv_control::AccelerationController --save=.```

I get the following error message:

```
/home/rafaelsaback/flatfish/bir_rock/tools/orogen/lib/orogen/loaders/aggregate.rb:76:in `find_task_library_from_task_model_name': NotImplementedError (NotImplementedError)
	from /home/rafaelsaback/flatfish/bir_rock/tools/orocos.rb/bin/oroconf:101:in `<main>'
```

**Comment by doudou** [comment]
This is an orocosrb bug. Could you test https://github.com/rock-core/tools-orocosrb/pull/90 ?

**Comment by rafaelsaback** [comment]
It has solved the problem. Closing this issue...
