### ISSUE TITLE
Orogen Internal error

### ISSUE THREAD

**Issue by jmachowinski** [orocos-toolchain/orogen#78]
Hey, 
my students managed to create an internal error with the attached
files. I can not see anything wrong with it. 
As a side node, this was actually a minimal test case to debug
a typelib issue. We have problems with typelib creating the
MemoryLayout for RegisterBit.

Orogen and Typelib are on master.
Bootstrapped using Ruby2.0 on Ubuntu 14.04.4

Any Ideas ?
Greetings
    Janosch

**Comment by jmachowinski** [comment]
bittest.orogen

name "bittest"
import_types_from "bittestTypes.hpp"

task_context "Task" do
    needs_configuration

    property "config_value", "bittest::Test"

    input_port "input", "/std/string"

    output_port "output", "int"

    periodic 0.1
end

**Comment by doudou** [comment]
> my students managed to create an internal error with the attached files.

Please run it with `--debug` and post the error message and backtrace.

Which importer are you using ?

**Comment by jmachowinski** [comment]
[debug.txt](https://github.com/orocos-toolchain/orogen/files/258737/debug.txt)

The only trace I get is :
===== Internal error =======
Please report the following error to the orogen developers
/home/scotch/entern/tools/orogen/bin/orogen:184: stack level too deep (SystemStackError)

**Comment by doudou** [comment]
It's a typelib bug, typelib crashes when computing the memory layout of /bittest/Test.

To ease debugging, Here are the offending tlb and a ruby script that triggers the bug

[bittest.tlb](https://github.com/orocos-toolchain/orogen/files/261933/bittest.tlb.txt)
[crash.rb](https://github.com/orocos-toolchain/orogen/files/261932/crash.rb.txt)

**Comment by doudou** [comment]
Should be fixed by https://github.com/orocos-toolchain/typelib/pull/82

**Comment by doudou** [comment]
Typelib pull request merged, I close this.
